config/routes.rb
Rails.application.routes.draw do

  devise_for :admins
  resources :posts
  resources :pages, param: :title

  root 'basic_page#refresh'
  
  match '/admin',   to: 'basic_page#admin',   via: 'get'
  match '/resume',  to: 'basic_page#resume',  via: 'get'
  # match '/blog',    to: 'posts#index',        via: 'get'
  # match '/refresh', to: 'basic_page#refresh', via: 'get'

  get '*path' => redirect { |p, req|
    req.flash[:notice] = "#{p[:path]} is unavailable";
   '/'
  }

  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/admin.rb
# Devise-based administrator for usage in the application. Admins can write posts,
# create comments, and basically manage the entire application at large.s

class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/post.rb
# A post written by an admin for usage on the site

class Post < ActiveRecord::Base
	extend FriendlyId
  friendly_id :title, use: :slugged

	has_many :comments, dependent: :destroy
	has_one_attached :banner_image

	validates :title, presence: true, length: { maximum: 150 }
	validates :body, presence: true, length: { minimum: 5 }

end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/basic_page_controller.rb
class BasicPageController < ApplicationController

  def index
    @posts = Post.where(published: true)
    @posts = @posts.order('created_at DESC').paginate(:page => params[:page], :per_page => 1)
  end

  def admin
    authenticate_admin!
    @admins = Admin.all
    @posts = Post.paginate(page: params[:page], per_page: 10).order('created_at DESC')
  end

  def refresh
  end

  def resume
    @content_class = "resume"
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

	before_action :authenticate_admin!, only: [:create, :new, :edit, :update, :destroy]
	before_action :find_post, only: [:show, :edit, :update, :destroy]

	def new
		@post = Post.new
	end

	def create
			@post = Post.new(post_params)
			if @post.save
	  		redirect_to posts_url, notice: 'Post was successfully created.'
	  	else
	  		render action: "new"
	  	end
	end

	def show
		@not_linkable = true
  	if @post.published == false
			redirect_to :back, notice: "The post you're trying to look at hasn't been published yet!"
		end
	end

	def destroy
		@post.destroy
		redirect_to admin_path
	end

	def index
		@page = if params[:page].present?
			params[:page]
		else
			1
		end
		
		@posts = Post.where(published: true)
		@at_last_page = (@posts.count / 10) == @page
		@posts = @posts.order('created_at DESC').paginate(:page => @page, :per_page => 10)
	end

	def edit
	end

	def update
		if @post.update(post_params)
			redirect_to edit_post_path(@post), notice: "Post was successfully updated"
		else
			render :edit
		end
	end

	private

		def find_post
			@post = Post.friendly.find(params[:id])
		end

		def post_params
			params.require(:post).permit(:title, :tagline, :published, :body, :banner_image)
		end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/api/v1/comments_helper.rb
module Api::V1::CommentsHelper
end

app/helpers/api/v1/pages_helper.rb
module Api::V1::PagesHelper
end

app/helpers/api/v1/posts_helper.rb
module Api::V1::PostsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

	def markdown(text)
		Commonmarker.to_html(text).html_safe
	end
end

app/views/basic_page/about_commenting.html.haml
.post
  .post-header
    .text-center
      %h1 What's Up With Commenting These Days?

  .post-content.center-block.row

    %p
      The other day, I had this idea for a new commenting system. I've spent my last
      few development sessions creating this commenting system. However, its a bit different
      than any other commenting system out there right now.

    %p Let's talk about it for a second.

    %h3 How I'm Implementing This System

    %p
      One of the hardest things on the internet is handling spam and encouraging good
      discourse. I really love #{link_to 'Discourse', 'https://www.discourse.org/', target: 'blank'} and their approach to
      the subject. However, I really wanted to try something different for this site.
    %p
      The approach I want to implement is simple:
      %b Hosting a Q&A or sorts between readers and myself.
      In the best scenario, every valid concern to a post would be addressed in a
      format that respects the initial commenter, but also allows for me to take time
      to address a comment before it gets lost down a thread.

    %p
      Right now, we've got a pretty nifty form that looks like something like this:

    = image_tag 'comment_form.png', :class => 'img img-responsive'

    %p
      Once you fill out the form, a comment will be sent to the admin panel of this site.
      From there, I'll be able to address the comment in the proper manner and send a response
      either privately or publicly (depending on what it warrants).

    %h3 Public Comment Responses

    %p
      If the comment is being addressed publically, then you'll see a section on the post
      that looks something like this:

    = image_tag 'comment-response.png', :class => 'img img-responsive'

    %h3 Private Comment Responses

    %p
      If I feel like a comment needs to be addressed privately, I'll be contacting you through
      the email provided in the comment.

    %p
      I'm also aware that this is an expiriment of sorts. So, please be patient with every bug
      and bump in the road. Maybe, at the end of all of this, we'll have something worth talking
      about!

app/views/basic_page/admin.html.erb
<div class="admin-posts-index">
  <h1>Listing Posts</h1>
  <table class="table table-striped table-hover">
    <thead>
      <tr>
        <th>Title</th>
        <th colspan="3">Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @posts.each do |post| %>
        <tr>
          <td>
            <%= post.title %>
          </td>
          <td>
            <%= link_to 'Edit', edit_post_path(post), class: "warning-button" %>
          </td>
          <td>
            <%= button_to 'Destroy', post_path(post), class: "danger-button", method: :delete, data: { confirm: 'Are you sure?' } %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <div class="has-text-centered mt-1">
    <%= link_to "New Post", new_post_path, class: "primary-button" %>
  </div>
</div>

app/views/basic_page/admin.html.haml
.posts-index
  %h1 Listing Posts

  %table.table.table-striped
    %tr
      %th Title
      %th{:colspan => "3"} Actions

    - @posts.each do |post|
      %tr
        %td= post.title
        %td= link_to 'Comments', post_comment_admin_path(post), :class => "btn btn-success"
        %td= link_to 'Edit', edit_post_path(post), :class => "btn btn-primary"
        %td= button_to 'Destroy', post_path(post), :class => "btn btn-danger", method: :delete, data: { confirm: 'Are you sure?' }

    .text-center
      = link_to "New Post", new_post_path, :class => "btn btn-primary"
      = will_paginate @posts, renderer: BootstrapPagination::Rails

.admins-index
  %h1 Listing Admins

  %table.table.table-striped
    %tr
      %th Email
      %th Role
      %th Sign In Count
      %th{:colspan => "3"} Actions


    - @admins.each do |admin|
      - if admin != current_admin
        %tr
          %td= admin.email
          %td= admin.role
          %td= admin.sign_in_count
          %td= link_to 'Delete', admin_registration_path(admin), :class => "btn btn-danger", method: :delete, data: { confirm: 'Are you sure?' }

.page-index
  %h1 Listing Pages

  %table.table.table-striped
    %tr
      %th Title
      %th{:colspan=>"3"} Actions

    - @pages.each do |page|
      %tr
        %td= page.title
        %td= link_to 'Show', page_path(page), :class => "btn btn-primary"
        %td= link_to 'Edit', edit_page_path(page), :class => "btn btn-primary"
        %td= link_to 'Delete', page_path(page), :class => "btn btn-danger", method: :delete, data: { confirm: 'Are you sure?' }

      .text-center
        = link_to "New Page", new_page_path, :class => "btn btn-primary"

.inquiries-index
  %h1 Listing Inquiries

  %table.table.table-striped
    %tr
      %th Name
      %th Company
      %th Email
      %th Phone
      %th Need By
      %th{:colspan => "3"}Actions

    - @inquiries.each do |inquiry|
      %tr
        %td= inquiry.name
        %td= inquiry.company
        %td= inquiry.email
        %td= inquiry.phone
        %td= inquiry.finish_date
        %td= link_to 'Show', inquiry_path(inquiry), :class => "btn btn-primary"
        %td= link_to 'Edit', edit_inquiry_path(inquiry), :class => "btn btn-primary"
        %td= link_to 'Delete', inquiry_path(inquiry), :class => "btn btn-danger", method: :delete, data: { confirm: 'Are you sure?' }

app/views/basic_page/index.html.erb
<div class="most-recent">
	<% @posts.each do |post| %>
		<%= render 'posts/full_post', post: post %>
	<% end %>
	
	<div class="has-text-centered">
		<%= link_to "More Posts", blog_path, class: "button" %>
	</div>
</div>

app/views/basic_page/taylor_jones.html.erb
<h1>About Taylor Jones</h1>
<div></div>
<div class="resume-wrapper">
	<h1>Resume</h1>
	<div class="Projects">
		<h2>Projects</h2>
			<uL>
				<li>Medical System - Medical Staff Management Mockup - ASP.NET / C# </li>
					<a href="https://github.com/CodedBeardedSignedTaylor/MedicalSystem">Github</a>
				<li>EverythingIsRuby - Source Code For This Site - Ruby </li>
					<a href="https://github.com/CodedBeardedSignedTaylor/EverythingIsRuby">Github</a>
				<li>Hours Tracker - Command Line Productivity - Ruby </li>
					<a href="https://github.com/CodedBeardedSignedTaylor/Hours-Tracker">Github</a>
			</uL>
	</div>

	<div class="Employement">
		<h2>Employment</h2>
		<ul>
			<h3>AQ2 Technologies <i>(January 2013 - August 2014)</i></h3>
			<li>Prominent remintance software producer out of Birmingham, AL</li>
			<li>Specialized in QA, Development, and Implementation of all products.</li>
			<li>Website: wwww.aq2tech.com</li>
		</ul>
		<ul>
			<h3>Freelance Web Design <i>(Janurary 2013 - Present)</i></h3>
			<li>Corresponded efficiently and effectively with clients</li>
			<li>Built full and robust application in Wordpress, Rails, and HTML</li>
			<li>Current taking on clients.</li>
		</ul>
	</div>

	<div class="Education">
		<h2>Education</h2>
		<uL>
			<h3>Auburn University - <i>(August 2010 - May 2015)</i></h3>
			<li>Major: Computer Science</li>
			<li>Minor: Business</li>
		</uL>
	</div>

	<div class="Links">
		<h2>Links</h2>
			<ul>
				<li><a href="www.github.com/codedbeardedsignedtaylor">Github</a></li>
				<li><a href="http://lnkd.in/b5h3XGJ">LinkedIn</a></li>
				<li><a href="">Email</a></li>
			</ul>
	</div>
</div>

app/views/layouts/application.html.erb
<%= render 'layouts/v2/layout' %>

app/views/layouts/v2/_alerts.html.erb
<div class="notification-banner">
    <% if notice %>
        <p class="notification is-success"><%= notice %></p>
    <% end %>
    <% if alert %>
        <p class="notification is-warning"><%= alert %></p>
    <% end %>
</div>

app/views/layouts/v2/_footer.html.erb
<footer class="footer">
	<div class="links">
		<p>Collateral Software - <%= Time.now.year %></p>
	</div>
</footer>

app/views/layouts/v2/_header.html.erb
<% if admin_signed_in? %>
  <div class="admin-banner">
    <%= link_to "Admin Dashboard", admin_path %>
    <%= link_to "Log Out", destroy_admin_session_path, method: :delete, class: "admin-action"%>
  </div>
<% end %>

<nav class="nav container">
  <div class="nav-logo-section">
    <%= link_to "Hi, I'm Taylor Jones", root_path, class: "nav-logo" %>
  </div>
  <div class="nav-spacer"></div>
  <div class="nav-menu">
    <button class="hamburger" data-action="sidebar#toggle" aria-label="Toggle menu">
      <span class="hamburger-line"></span>
      <span class="hamburger-line"></span>
      <span class="hamburger-line"></span>
    </button>
  </div>
</nav>

app/views/layouts/v2/_layout.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hi, I'm Taylor Jones</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Font stuff -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto+Condensed:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet">

    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">

    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

  </head>

  <body data-controller="sidebar">
    <div class="page-wrapper">
      <%= render 'layouts/v2/header' %>
      <div class="main-content container">
        <%= render 'layouts/v2/alerts' %>
        <div class="column wide-2"></div>
        <div class="column wide-6 <%= @content_class %>">
          <%= yield %>
        </div>
        <div class="column wide-2"></div>
      </div>
      <%= render 'layouts/v2/footer' %>
    </div>

    <aside class="sidebar" data-sidebar-target="panel">
      <button class="sidebar-close" data-action="sidebar#toggle" aria-label="Close menu">&times;</button>
      <ul class="sidebar-nav">
        <li><%= link_to "Posts", posts_path %></li>
        <li><%= link_to "Resume", "/resume" %></li>
      </ul>
    </aside>
  </body>
</html>
   

app/views/posts/_comment_form.html.erb
<h2>Add a comment:</h2>
<%= form_for([@post, @post.comments.build]) do |f| %>
  <p>
    <%= f.label :commenter %><br>
    <%= f.text_field :commenter %>
  </p>
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/posts/_form.html.erb
<%= form_for @post, html: { multipart: true } do |f| %>
  <% if @post.errors.any? %>
  <div class="form-errors">
    <h2><%= pluralize(@post.errors.count, "error") %> prohibited
      this post from being saved:</h2>
    <ul>
    <% @post.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-input" %>
  </div>

  <div class="form-group">
    <%= f.label :banner_image %>
    <%= f.file_field :banner_image, direct_upload: true %>
  </div>

  <% if @post.banner_image.attached? %>
    <div class="form-group">
      <%= image_tag @post.banner_image, class: "form-image-preview" %>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :tagline %>
    <%= f.text_field :tagline, class: "form-input" %>
  </div>

  <div class="form-checkbox">
    <%= f.label :published do %>
      <%= f.check_box :published %>
      Published
    <% end %>
  </div>

  <div class="form-group">
    <%= f.label :body %>
    <%= f.text_area :body, placeholder: "Enter Post Content Here.", class: "form-textarea", rows: 25 %>
  </div>

  <div class="form-actions">
    <%= link_to "Back", back_path, class: "primary-button" %>
    <%= f.submit class: "primary-button" %>
  </div>
<% end %>

app/views/posts/_full_post.html.erb
<div class="columns">
	<div class="column">
		<div class="post content">
			<div class="post-header">
				<% if post.banner_image.attached? %>
					<%= image_tag post.banner_image.service_url %>
				<% end %>
				<h1><%= link_to post.title, post_path(post) %></h1>
				<h3><i><%= post.tagline %></i></h3>
				<p>
					Written on <b><%= post.created_at.strftime("%B %d, %Y") %></b><br />				
				</p>
			</div>

			<div class="post-content center-block row">
				<%= markdown post.body %>
				<% if post.updated_at != post.created_at %>
					<p>Updated on <b><%= post.updated_at.strftime("%B %d, %Y") %></b></p>
				<% end %>
			</div>

			<div class="bottom-nav has-text-centered">
				<% if admin_signed_in? %>
					<br />
					<%= link_to 'Edit Post', edit_post_path(post.friendly_id), class: "button" %>
				<% end %>
			</div>
		</div>
	</div>
</div>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>

<%= render "form", back_path: admin_path %>

app/views/posts/index.html.erb
<% @posts.each do |post| %>
	<%= render 'posts/full_post', post: post%>
	<div class="content-divider"></div>
<% end %>

<% if @page != 1 && @posts.length > 1 %>
	<button class="button">Show Older</button>
<% end %>

<% if !@at_last_page %>
	<button class="button">Show Newer</button>
<% end %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render "form", back_path: posts_path %>

app/views/posts/partials/_form.html.erb
<%= form_for @post do |f| %>
  <% if @post.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@post.errors.count, "error") %> prohibited
      this article from being saved:</h2>
    <ul>
    <% @post.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/posts/show.html.erb
<%= render 'full_post', post: @post %>